// packages/react/src/RecordCollection.tsx
"use client";
import * as React from "react";
import { DataTable, type DataTableProps } from "./DataTable.js";
import {
  BulkActionBar,
  FilterBar,
  type BulkActionBarProps,
  type FilterBarProps,
} from "./patterns.js";
import type { DataRow, TableQuery } from "./business.js";

export interface RecordCollectionProps<
  T extends DataRow = DataRow,
> extends Pick<
  DataTableProps<T>,
  | "label"
  | "columns"
  | "rows"
  | "loadRows"
  | "getRowId"
  | "rowLabel"
  | "isRowSelectable"
  | "renderCell"
> {
  query: TableQuery;
  onQueryChange: (query: TableQuery) => void;
  selected: string[];
  onSelectedChange: (keys: string[]) => void;
  filters?: FilterBarProps["filters"];
  onFilterChange?: FilterBarProps["onFilterChange"];
  onResetFilters?: () => void;
  searchLabel?: string;
  /** Optional authoritative count. Omit while a server total is unknown. */
  resultCount?: number;
  toolbar?: React.ReactNode;
  bulkActions?: React.ReactNode;
  bulkBusy?: boolean;
  bulkResult?: BulkActionBarProps["result"];
  onRetryBulkActions?: () => void;
  /** Runs after requesting an empty selection, e.g. to dismiss bulk results. */
  onClearSelection?: () => void;
}

/**
 * The feature owns query, selection, filter values and operation results.
 * Facets are presentation data: apply them to local rows or capture them in
 * loadRows. DataTable alone owns local search/sort/pagination and remote request
 * cancellation; remote results are never filtered again by this composition.
 * Search, facet edits and reset request page 1. Selection survives query changes
 * until the feature changes it or the user explicitly clears it.
 */
export function RecordCollection<T extends DataRow>({
  label,
  columns,
  rows,
  loadRows,
  getRowId,
  rowLabel,
  isRowSelectable,
  renderCell,
  query,
  onQueryChange,
  selected,
  onSelectedChange,
  filters = [],
  onFilterChange,
  onResetFilters,
  searchLabel = `${label} 검색`,
  resultCount,
  toolbar,
  bulkActions,
  bulkBusy,
  bulkResult,
  onRetryBulkActions,
  onClearSelection,
}: RecordCollectionProps<T>) {
  const changeSearch = (search: string) =>
    onQueryChange({ ...query, page: 1, search });
  const changeFilter = (id: string, value: string) => {
    onFilterChange?.(id, value);
    if (query.page !== 1) onQueryChange({ ...query, page: 1 });
  };
  const resetFilters = () => {
    onQueryChange({ ...query, page: 1, search: "" });
    // Let the feature deliberately extend the reset (e.g. sort or page size).
    onResetFilters?.();
  };
  const clearSelection = () => {
    onSelectedChange([]);
    onClearSelection?.();
  };
  const showBulk = selected.length > 0 || bulkBusy || !!bulkResult;

  return (
    <section className="cheese-record-collection" aria-label={label}>
      <FilterBar
        label={`${label} 검색 및 필터`}
        search={query.search}
        onSearchChange={changeSearch}
        searchLabel={searchLabel}
        filters={filters}
        onFilterChange={changeFilter}
        onReset={resetFilters}
        resultCount={resultCount}
      />
      {toolbar && (
        <div className="cheese-record-collection-toolbar">{toolbar}</div>
      )}
      {showBulk && (
        <div className="cheese-record-collection-selection">
          <BulkActionBar
            selectedCount={selected.length}
            actions={[]}
            onClear={clearSelection}
            busy={bulkBusy}
            result={bulkResult}
            onRetry={onRetryBulkActions}
          />
          {bulkActions && (
            <div className="cheese-record-collection-actions">
              {bulkActions}
            </div>
          )}
        </div>
      )}
      <DataTable
        label={label}
        columns={columns}
        rows={rows}
        loadRows={loadRows}
        getRowId={getRowId}
        rowLabel={rowLabel}
        isRowSelectable={isRowSelectable}
        query={query}
        onQueryChange={onQueryChange}
        selected={selected}
        onSelectedChange={onSelectedChange}
        showSearch={false}
        showSelectionSummary={false}
        renderCell={renderCell}
      />
    </section>
  );
}

// packages/vue/src/RecordCollection.vue
<script setup lang="ts" generic="T extends DataRow">
import DataTable from "./DataTable.vue";
import FilterBar from "./patterns/FilterBar.vue";
import BulkActionBar from "./patterns/BulkActionBar.vue";
import type { DataRow, RowsLoader, TableColumn, TableQuery } from "./business";
import type { BulkActionResult, FilterBarFilter } from "./patterns/types";

/**
 * The feature owns query, selection, filter values and operation results.
 * Apply facets to local rows or capture them in loadRows. DataTable retains
 * local querying and remote cancellation; this composition never filters a
 * remote result. Query changes retain selection until it is explicitly cleared.
 */
const props = defineProps<{
  label: string;
  columns: TableColumn[];
  rows?: T[];
  loadRows?: RowsLoader<T>;
  getRowId: (row: T) => string;
  rowLabel?: (row: T) => string;
  isRowSelectable?: (row: T) => boolean;
  query: TableQuery;
  selected: string[];
  filters?: FilterBarFilter[];
  searchLabel?: string;
  /** Optional authoritative count; omit while a server total is unknown. */
  resultCount?: number;
  bulkBusy?: boolean;
  bulkResult?: BulkActionResult;
  bulkRetryable?: boolean;
}>();
const emit = defineEmits<{
  "update:query": [query: TableQuery];
  "query-change": [query: TableQuery];
  "update:selected": [keys: string[]];
  "filter-change": [id: string, value: string];
  "reset-filters": [];
  "clear-selection": [];
  "retry-bulk-actions": [];
}>();
defineSlots<{
  toolbar?(): unknown;
  "bulk-actions"?(): unknown;
  cell?(props: { row: T; column: TableColumn }): unknown;
}>();

function changeQuery(query: TableQuery) {
  emit("update:query", query);
  emit("query-change", query);
}
function changeSearch(search: string) {
  changeQuery({ ...props.query, page: 1, search });
}
function changeFilter(id: string, value: string) {
  emit("filter-change", id, value);
  if (props.query.page !== 1) changeQuery({ ...props.query, page: 1 });
}
function resetFilters() {
  changeQuery({ ...props.query, page: 1, search: "" });
  // A feature may extend the default query reset in this callback.
  emit("reset-filters");
}
function clearSelection() {
  emit("update:selected", []);
  emit("clear-selection");
}
</script>

<template>
  <section class="cheese-record-collection" :aria-label="label">
    <FilterBar
      :label="`${label} 검색 및 필터`"
      :search="query.search"
      :search-label="searchLabel ?? `${label} 검색`"
      :filters="filters ?? []"
      :result-count="resultCount"
      @update:search="changeSearch"
      @filter-change="changeFilter"
      @reset="resetFilters"
    />
    <div v-if="$slots.toolbar" class="cheese-record-collection-toolbar">
      <slot name="toolbar" />
    </div>
    <div
      v-if="selected.length || bulkBusy || bulkResult"
      class="cheese-record-collection-selection"
    >
      <BulkActionBar
        :selected-count="selected.length"
        :actions="[]"
        :busy="bulkBusy"
        :result="bulkResult"
        :retryable="bulkRetryable"
        @clear="clearSelection"
        @retry="emit('retry-bulk-actions')"
      />
      <div
        v-if="$slots['bulk-actions']"
        class="cheese-record-collection-actions"
      >
        <slot name="bulk-actions" />
      </div>
    </div>
    <DataTable
      :label="label"
      :columns="columns"
      :rows="rows"
      :load-rows="loadRows"
      :get-row-id="getRowId"
      :row-label="rowLabel"
      :is-row-selectable="isRowSelectable"
      :query="query"
      :selected="selected"
      :show-search="false"
      :show-selection-summary="false"
      @update:query="changeQuery"
      @update:selected="emit('update:selected', $event)"
    >
      <template v-if="$slots.cell" #cell="{ row, column }">
        <slot name="cell" :row="row" :column="column" />
      </template>
    </DataTable>
  </section>
</template>
